export const techIcons: Record<string, string> = {
  Angular: '/icons/tech/angular.svg',
  JavaScript: '/icons/tech/javascript.svg',
  React: '/icons/tech/react.svg',
  TypeScript: '/icons/tech/typescript.svg',
  'Vue.js': '/icons/tech/vuejs.svg',
  '.NET': '/icons/tech/dotnet.svg',
  'C#': '/icons/tech/csharp.svg',
  Django: '/icons/tech/django.svg',
  Golang: '/icons/tech/golang.svg',
  Java: '/icons/tech/java.svg',
  'Node.js': '/icons/tech/nodejs.svg',
  PHP: '/icons/tech/php.svg',
  Python: '/icons/tech/python.svg',
  Ruby: '/icons/tech/ruby.svg',
  AWS: '/icons/tech/aws.svg',
  'Google Cloud': '/icons/tech/googlecloud.svg',
  'Microsoft Azure': '/icons/tech/azure.svg',
  'Power BI': '/icons/tech/powerbi.svg',
  Salesforce: '/icons/tech/salesforce.svg',
  AI: '/icons/tech/ai.svg',
  'C++': '/icons/tech/cplusplus.svg',
  Kotlin: '/icons/tech/kotlin.svg',
  'Machine Learning': '/icons/tech/machinelearning.svg',
  Xamarin: '/icons/tech/xamarin.svg',
}
